#!/usr/bin/env node
// Compiles src/elements/tailwind.css with the Tailwind v4 CLI and inlines the
// result into src/elements/tailwind.generated.ts as an exported string. The
// widget adopts that string into its shadow root (src/mount.tsx), so the CSS
// ships inside the JS bundle with zero loader coordination — same trick as
// src/styles.ts. Wired as css/predev/prebuild/pretest in package.json.
//
// Idempotent: skips the write when the output is byte-identical. Fails loudly:
// any CLI error or implausibly small output exits non-zero.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import { createRequire } from "node:module";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const input = path.join(packageRoot, "src", "elements", "tailwind.css");
const output = path.join(packageRoot, "src", "elements", "tailwind.generated.ts");

if (!fs.existsSync(input)) {
  console.error(`build-css: missing input ${input}`);
  process.exit(1);
}

// Resolve the CLI entry from this package's own dependency graph (not PATH,
// not a hoisted bin) so the build behaves identically in any pnpm layout.
const cliPkgPath = require.resolve("@tailwindcss/cli/package.json", { paths: [packageRoot] });
const cliPkg = require(cliPkgPath);
const cliBin = path.join(path.dirname(cliPkgPath), cliPkg.bin.tailwindcss);

const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "phillip-tailwind-"));
const tmpOut = path.join(tmpDir, "tailwind.css");

let css;
try {
  execFileSync(process.execPath, [cliBin, "-i", input, "-o", tmpOut, "--minify"], {
    cwd: packageRoot,
    stdio: ["ignore", "ignore", "inherit"], // surface CLI errors, swallow its "Done in Xms" chatter
  });
  css = fs.readFileSync(tmpOut, "utf8").trim();
} catch (error) {
  console.error("build-css: tailwind CLI failed");
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
} finally {
  fs.rmSync(tmpDir, { recursive: true, force: true });
}

// A working build always contains our @theme palette; an empty/near-empty file
// means the source scan silently matched nothing. Refuse to ship that.
if (css.length < 500 || !css.includes("--color-brand-600")) {
  console.error(
    `build-css: suspicious output (${css.length} bytes) — check @source globs in src/elements/tailwind.css`,
  );
  process.exit(1);
}

// Emitted as a template literal: biome's formatter never re-wraps or
// re-quotes those, so `biome check --write` and this generator agree on every
// byte (a JSON.stringify'd double-quoted string gets reflowed by biome).
const escaped = css.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
const generated = `// GENERATED by scripts/build-css.mjs — do not edit.
// Compiled from src/elements/tailwind.css (Tailwind v4). Regenerate: pnpm css
export const tailwindStyles = \`${escaped}\`;
`;

if (fs.existsSync(output) && fs.readFileSync(output, "utf8") === generated) {
  console.log(`build-css: ${path.relative(packageRoot, output)} unchanged (${css.length} bytes)`);
} else {
  fs.writeFileSync(output, generated);
  console.log(
    `build-css: wrote ${path.relative(packageRoot, output)} (${css.length} bytes of css)`,
  );
}
